// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mo.app.mercury.domain.serviceagent.entity;


privileged aspect ServiceAgentEntity_Roo_ToString {
    
    public String ServiceAgentEntity.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AgentBandRating: ").append(getAgentBandRating()).append(", ");
//        sb.append("AuthorisationToleranceAmount: ").append(getAuthorisationToleranceAmount()).append(", ");
//        sb.append("AuthorisationTolerancePc: ").append(getAuthorisationTolerancePc()).append(", ");
//        sb.append("Comments: ").append(getComments()).append(", ");
//        sb.append("FranchiseOnly: ").append(getFranchiseOnly()).append(", ");
//        sb.append("Id: ").append(getId()).append(", ");
//        sb.append("InvoiceToleranceAmount: ").append(getInvoiceToleranceAmount()).append(", ");
//        sb.append("InvoiceTolerancePc: ").append(getInvoiceTolerancePc()).append(", ");
//        sb.append("MaintenanceAgentMaag: ").append(getMaintenanceAgentMaag()).append(", ");
//        sb.append("ReferAllIndic: ").append(getReferAllIndic()).append(", ");
//        sb.append("ReferralContact: ").append(getReferralContact()).append(", ");
//        sb.append("ReferralLimitAuto: ").append(getReferralLimitAuto()).append(", ");
//        sb.append("ReferralLimitNonAuto: ").append(getReferralLimitNonAuto()).append(", ");
//        sb.append("ReferralPhoneNumber: ").append(getReferralPhoneNumber()).append(", ");
//        sb.append("Timestamp: ").append(getTimestamp()).append(", ");
//        sb.append("TlSpecialParts: ").append(getTlSpecialParts() == null ? "null" : getTlSpecialParts().size()).append(", ");
//        sb.append("TransmissionAction: ").append(getTransmissionAction()).append(", ");
        return sb.toString();
    }
    
}
