// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mo.app.mercury.domain.agreement.entity;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AgreementExtensionAuditEntity_Roo_Configurable {
    
    declare @type: AgreementExtensionAuditEntity: @Configurable;
    
}
